<h2 align="center" style="color:blue">Codebasics Python Course: Numpy Introduction & Benefits </h2>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

<h3 align="center">Numpy Array vs Python List</h3>

### Benefit # 1: Less Memory

In [7]:
import sys

python_list = list(range(100))
python_list[:4]

[0, 1, 2, 3]

In [8]:
sys.getsizeof(python_list[0])

24

In [9]:
sys.getsizeof(python_list[0])*len(python_list)

2400

In [14]:
numpy_array = np.arange(100)
numpy_array[:4]

array([0, 1, 2, 3])

In [15]:
numpy_array.nbytes

400

As you can see above while numpy array occupies only 400 bytes, the same size list in Python will require 2400 bytes. This shows that numpy arrays are memory efficient

### Benefit # 2: Speed

In [25]:
import time

SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x, y in zip(l1, l2)]
end_time = time.time()
print("Python list took: ", end_time-start_time)

Python list took:  0.0516204833984375


In [26]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:3], n2[:3]

(array([0, 1, 2]), array([0, 1, 2]))

In [36]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.0021076202392578125


### Benefit # 3: Convenient Use with Built In Functions

In [38]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3], l2[:3]

([0, 1, 2], [0, 1, 2])

In [39]:
l1 + l2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [40]:
l3 = [x+y for x, y in zip(l1, l2)]
l3

[0, 2, 4, 6, 8]

In [44]:
n1 = np.arange(5)
n2 = np.arange(5)
n1, n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [46]:
n3 = n1 + n2
n3

array([0, 2, 4, 6, 8])

In [47]:
n3 = n1*n2
n3

array([ 0,  1,  4,  9, 16])