In [1]:
import numpy as np

### Multiple dimensions in numpy arrays

In [72]:
# revenues of quarter 1
rev_q1 = np.array([10, 12, 9])
rev_q1.ndim

1

In [73]:
# revenues of quarter 1 and 2
rev = np.array([[10, 12, 9],[15, 11, 13]])
rev.ndim

2

### Indexing

In [74]:
# find revenues of first month of second quarter
rev[1,0]

15

In [75]:
# update revenue of first month of second quarter
rev[1,0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

### Data type

In [76]:
rev.dtype

dtype('int32')

In [77]:
rev.itemsize

4

In [78]:
rev = np.array([[10, 12, 9],[15, 11, 13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [79]:
rev.itemsize

8

In [80]:
rev.size

6

In [81]:
rev.shape

(2, 3)

### Sorting

In [113]:
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

### Zeros, Ones, arange, linspace

In [32]:
# this kind of array is useful to initialize neural network weights
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.arange(3)

array([0, 1, 2])

In [35]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [40]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

### flatten, reshape, min, max

In [82]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [83]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [84]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [86]:
rev.reshape(3,2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [92]:
rev.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [88]:
rev.min() # minimum revenue

9.0

In [89]:
rev.max() # maximum revenue

15.0

### sum

In [96]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [100]:
rev.sum(axis=0) # total revenue of first, second and third month of Q1 and Q2

array([25., 23., 22.])

In [101]:
rev.sum(axis=1) # total Q1 and Q2 revenue

array([31., 39.])

In [111]:
for row in rev:
    print("row: ", row)

row:  [10. 12.  9.]
row:  [15. 11. 13.]


In [108]:
b = np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [109]:
np.square(b)

array([  1,  16, 256])

In [104]:
np.std(b)

6.48074069840786